<?php
declare(strict_types=1);

return [
    'gymbeam-true-whey' => [
        'slug' => 'gymbeam-true-whey',
        'name' => 'GymBeam True Whey',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'proteiny',
        'affiliate_code' => 'protein-na-chudnutie-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/true-whey-gymbeam.html',
        'summary' => 'Prakticky whey protein na kazdy den a lepsi rozpocet.',
        'image' => [
            'remote_src' => 'https://gymbeam.sk/media/catalog/product/cache/bf5a31e851f50f3ed6850cbbf183db11/p/r/protei_n_true_whey_-_gymbeam_2500_g_-_vanilla.png',
            'alt' => 'GymBeam True Whey',
            'width' => 1000,
            'height' => 1000,
        ],
        'pros' => ['dobra cena na porciu', 'univerzalne pouzitie po treningu aj cez den'],
        'cons' => ['nie je to najcistejsi WPI profil'],
        'feed_source' => 'gymbeam-heureka-xml',
        'merchant_product_id' => null,
        'image_source' => 'merchant-feed',
    ],
    'gymbeam-just-whey' => [
        'slug' => 'gymbeam-just-whey',
        'name' => 'GymBeam Just Whey',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'proteiny',
        'affiliate_code' => 'najlepsie-proteiny-2025-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/just-whey-gymbeam.html',
        'summary' => 'Silnejsi premium whey variant pre hlavny top vyber.',
        'image' => [
            'remote_src' => 'https://gymbeam.sk/media/catalog/product/cache/bf5a31e851f50f3ed6850cbbf183db11/j/u/just_whey_vanilla_icecream_1_kg_gymbeam_1.png',
            'alt' => 'GymBeam Just Whey',
            'width' => 1000,
            'height' => 1000,
        ],
        'pros' => ['silny pomer chut a pouzitelnost', 'vhodne aj ako hlavny odporucany whey'],
        'cons' => ['vyssia cena ako basic whey'],
        'feed_source' => 'gymbeam-heureka-xml',
        'merchant_product_id' => null,
        'image_source' => 'merchant-feed',
    ],
    'gymbeam-creatine-monohydrate-real' => [
        'slug' => 'gymbeam-creatine-monohydrate-real',
        'name' => 'GymBeam 100% Kreatin monohydrat',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'kreatin',
        'affiliate_code' => 'kreatin-porovnanie-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/kreatin-monohydrate-gymbeam.html',
        'summary' => 'Zakladny monohydrat pre dlhodobe kazdodenne davkovanie.',
        'image' => [
            'remote_src' => 'https://gymbeam.sk/media/catalog/product/cache/bf5a31e851f50f3ed6850cbbf183db11/c/r/creatine_monohydrate_unflavoured_250_g_gymbeam.png',
            'alt' => 'GymBeam 100% Kreatin monohydrat',
            'width' => 1000,
            'height' => 1000,
        ],
        'pros' => ['najjednoduchsi a overeny kreatinovy zaklad', 'ciste zlozenie'],
        'cons' => ['benefit pride az pri pravidelnom uzivani'],
        'feed_source' => 'gymbeam-heureka-xml',
        'merchant_product_id' => null,
        'image_source' => 'merchant-feed',
    ],
    'gymbeam-magnesium-citrate-caps' => [
        'slug' => 'gymbeam-magnesium-citrate-caps',
        'name' => 'GymBeam Magnesium Citrate Caps',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'mineraly',
        'affiliate_code' => 'horcik-ktory-je-najlepsi-a-preco-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/magnezium-citrat-caps-gymbeam.html',
        'summary' => 'Univerzalna forma horcika na bezne kazdodenne pouzitie.',
        'image' => [
            'remote_src' => 'https://gymbeam.sk/media/catalog/product/cache/bf5a31e851f50f3ed6850cbbf183db11/m/a/magnesium_citrate_120_vegan_caps_gymbeam.png',
            'alt' => 'GymBeam Magnesium Citrate Caps',
            'width' => 1000,
            'height' => 1000,
        ],
        'pros' => ['prakticke kapsuly', 'dobra everyday volba'],
        'cons' => ['citrat nemusi sadnut kazdemu citlivemu traveniu'],
        'feed_source' => 'gymbeam-heureka-xml',
        'merchant_product_id' => null,
        'image_source' => 'merchant-feed',
    ],
    'gymbeam-probioten' => [
        'slug' => 'gymbeam-probioten',
        'name' => 'ProbioTen - GymBeam',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'probiotika-travenie',
        'affiliate_code' => 'probiotika-ako-vybrat-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/probioten-gymbeam.html',
        'summary' => 'Prakticke probiotika pre bezny rezim a citlivejsie travenie.',
        'image' => [
            'remote_src' => 'https://gymbeam.sk/media/catalog/product/cache/bf5a31e851f50f3ed6850cbbf183db11/p/r/probioten_60_caps_gymbeam.png',
            'alt' => 'ProbioTen - GymBeam',
            'width' => 1000,
            'height' => 1000,
        ],
        'pros' => ['jednoduche davkovanie', 'vhodne pre bezny dlhsi rezim'],
        'cons' => ['nie je to specializovany post-antibiotic produkt'],
        'feed_source' => 'gymbeam-heureka-xml',
        'merchant_product_id' => null,
        'image_source' => 'merchant-feed',
    ],
    'gymbeam-enjoy-pre-workout' => [
        'slug' => 'gymbeam-enjoy-pre-workout',
        'name' => 'GymBeam ENJOY Pre-Workout',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'pre-workout',
        'affiliate_code' => 'pre-workout-ako-vybrat-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/enjoy-pre-workout-gymbeam.html',
        'summary' => 'Komplexny GymBeam pre-workout pre vykon, fokus a pumpu.',
        'image' => [
            'remote_src' => 'https://gymbeam.sk/media/catalog/product/cache/bf5a31e851f50f3ed6850cbbf183db11/e/n/enjoy_preworkout_dragon_fruit_312_g_gymbeam.png',
            'alt' => 'GymBeam ENJOY Pre-Workout',
            'width' => 1000,
            'height' => 1000,
        ],
        'pros' => ['all in one pre-workout formula', 'jasne zrozumitelna produktova stranka'],
        'cons' => ['nie je vhodny neskoro vecer'],
        'feed_source' => 'gymbeam-heureka-xml',
        'merchant_product_id' => null,
        'image_source' => 'merchant-feed',
    ],
    'gymbeam-runcollg-collagen' => [
        'slug' => 'gymbeam-runcollg-collagen',
        'name' => 'GymBeam RunCollg Collagen',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'klby-koza',
        'affiliate_code' => 'kolagen-na-klby-porovnanie-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/hydrolyzovany-kolagen-runcollgr-gymbeam.html',
        'summary' => 'Hydrolyzovany kolagen pre kazdodenny rezim a klbovy support.',
        'image' => [
            'remote_src' => 'https://gymbeam.sk/media/catalog/product/cache/bf5a31e851f50f3ed6850cbbf183db11/h/y/hydrolyzed_collagen_runcollg_orange_500_g_gymbeam.png',
            'alt' => 'GymBeam RunCollg Collagen',
            'width' => 1000,
            'height' => 1000,
        ],
        'pros' => ['jednoduchy kazdodenny kolagenovy zaklad', 'merchant feed ma kvalitny produktovy obrazok'],
        'cons' => ['nie je to specializovana volba cisto na klbovy typ II fokus'],
        'feed_source' => 'gymbeam-heureka-xml',
        'merchant_product_id' => null,
        'image_source' => 'merchant-feed',
    ],
    'gymbeam-vegan-blend' => [
        'slug' => 'gymbeam-vegan-blend',
        'name' => 'GymBeam Vegan Blend',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'proteiny',
        'affiliate_code' => 'veganske-proteiny-top-vyber-2025-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/protein-vegan-blend-gymbeam.html',
        'summary' => 'Rastlinny proteinovy blend ako silny zaklad pre vegan vyber.',
        'image' => [
            'remote_src' => 'https://gymbeam.sk/media/catalog/product/cache/bf5a31e851f50f3ed6850cbbf183db11/p/r/protein_vegan_blend_1000_g_chocolate_gymbeam.png',
            'alt' => 'GymBeam Vegan Blend',
            'width' => 1000,
            'height' => 1000,
        ],
        'pros' => ['priamo sedi na vegan kategoriu a buying guide', 'merchant feed ma stabilnu produktovu URL'],
        'cons' => ['nie kazdemu sadne chut a konzistencia rastlinneho blendu'],
        'feed_source' => 'gymbeam-heureka-xml',
        'merchant_product_id' => null,
        'image_source' => 'merchant-feed',
    ],
];
