<?php
declare(strict_types=1);

return [
    'aktin-whey-isolate-cut' => [
        'slug' => 'aktin-whey-isolate-cut',
        'name' => 'Whey Isolate / nízkokalorický WPI',
        'merchant' => 'Aktin',
        'merchant_slug' => 'aktin',
        'category' => 'proteiny',
        'affiliate_code' => 'protein-na-chudnutie-aktin',
        'fallback_url' => 'https://www.aktin.sk/',
        'summary' => 'Čistejší proteínový profil vhodný do diéty a pri nižšej tolerancii laktózy.',
        'image' => [
            'asset' => 'img/products/aktin-whey-isolate-cut/main.webp',
            'alt' => 'Produktový placeholder pre whey isolate od Aktinu',
        ],
        'pros' => ['nižší obsah cukrov a laktózy', 'praktické pri redukcii'],
        'cons' => ['vyššia cena za porciu'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'gymbeam-whey-concentrate-value' => [
        'slug' => 'gymbeam-whey-concentrate-value',
        'name' => 'Whey koncentrát / value voľba',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'proteiny',
        'affiliate_code' => 'protein-na-chudnutie-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/',
        'summary' => 'Dobrá cena na každodenné použitie, ak chceš držať rozpočet nižšie.',
        'image' => [
            'asset' => 'img/products/gymbeam-whey-concentrate-value/main.webp',
            'alt' => 'Produktový placeholder pre whey koncentrát GymBeam',
        ],
        'pros' => ['dobrá cena na dávku', 'praktické každodenné použitie'],
        'cons' => ['viac treba sledovať príchute a cukry'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'myprotein-clear-protein-light' => [
        'slug' => 'myprotein-clear-protein-light',
        'name' => 'Clear protein / ľahší drink',
        'merchant' => 'Myprotein',
        'merchant_slug' => 'myprotein',
        'category' => 'proteiny',
        'affiliate_code' => 'protein-na-chudnutie-myprotein',
        'fallback_url' => 'https://www.myprotein.sk/',
        'summary' => 'Sviežejší proteínový drink pre ľudí, ktorým nesedia hutné mliečne shake-y.',
        'image' => [
            'asset' => 'img/products/myprotein-clear-protein-light/main.webp',
            'alt' => 'Produktový placeholder pre clear protein Myprotein',
        ],
        'pros' => ['ľahší profil na pitie', 'praktické v teplejšom období'],
        'cons' => ['zasýti menej ako klasický whey'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'aktin-creatine-monohydrate' => [
        'slug' => 'aktin-creatine-monohydrate',
        'name' => 'Creatine Monohydrate / osvedčený základ',
        'merchant' => 'Aktin',
        'merchant_slug' => 'aktin',
        'category' => 'kreatin',
        'affiliate_code' => 'kreatin-porovnanie-aktin',
        'fallback_url' => 'https://www.aktin.sk/',
        'summary' => 'Najistejšia forma kreatínu z pohľadu dát aj dlhodobého používania.',
        'image' => [
            'asset' => 'img/products/aktin-creatine-monohydrate/main.webp',
            'alt' => 'Produktový placeholder pre kreatín monohydrát Aktin',
        ],
        'pros' => ['najsilnejšie dôkazy zo všetkých foriem', 'jednoduché dávkovanie'],
        'cons' => ['treba pravidelnosť, nie jednorazové použitie'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'gymbeam-creatine-monohydrate' => [
        'slug' => 'gymbeam-creatine-monohydrate',
        'name' => 'Kreatín monohydrát / value',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'kreatin',
        'affiliate_code' => 'kreatin-porovnanie-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/',
        'summary' => 'Dobrá value voľba na dlhodobé každodenné dávkovanie kreatínu.',
        'image' => [
            'asset' => 'img/products/gymbeam-creatine-monohydrate/main.webp',
            'alt' => 'Produktový placeholder pre kreatín GymBeam',
        ],
        'pros' => ['praktická cena', 'jednoduchý základ bez hype foriem'],
        'cons' => ['menej odlišný produktový positioning'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'myprotein-creatine-hcl' => [
        'slug' => 'myprotein-creatine-hcl',
        'name' => 'Kreatín HCl / alternatíva',
        'merchant' => 'Myprotein',
        'merchant_slug' => 'myprotein',
        'category' => 'kreatin',
        'affiliate_code' => 'kreatin-monohydrat-vs-hcl-myprotein',
        'fallback_url' => 'https://www.myprotein.sk/',
        'summary' => 'Alternatíva pre tých, čo chcú menšiu dávku a lepšiu rozpustnosť.',
        'image' => [
            'asset' => 'img/products/myprotein-creatine-hcl/main.webp',
            'alt' => 'Produktový placeholder pre kreatín HCl Myprotein',
        ],
        'pros' => ['dobrá rozpustnosť', 'menšia dávka'],
        'cons' => ['menej presvedčivých dát ako monohydrát'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'aktin-magnesium-bisglycinate' => [
        'slug' => 'aktin-magnesium-bisglycinate',
        'name' => 'Magnézium bisglycinát',
        'merchant' => 'Aktin',
        'merchant_slug' => 'aktin',
        'category' => 'mineraly',
        'affiliate_code' => 'horcik-ktory-je-najlepsi-a-preco-aktin',
        'fallback_url' => 'https://www.aktin.sk/',
        'summary' => 'Šetrná forma horčíka vhodná na večer, stres a citlivejší žalúdok.',
        'image' => [
            'asset' => 'img/products/aktin-magnesium-bisglycinate/main.webp',
            'alt' => 'Produktový placeholder pre horčík bisglycinát Aktin',
        ],
        'pros' => ['dobrá tolerancia', 'hodí sa pri strese a spánku'],
        'cons' => ['zvyčajne vyššia cena ako oxid alebo citrát'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'gymbeam-magnesium-citrate' => [
        'slug' => 'gymbeam-magnesium-citrate',
        'name' => 'Magnézium citrát',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'mineraly',
        'affiliate_code' => 'horcik-ktory-je-najlepsi-a-preco-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/',
        'summary' => 'Univerzálna forma horčíka na každodenné použitie.',
        'image' => [
            'asset' => 'img/products/gymbeam-magnesium-citrate/main.webp',
            'alt' => 'Produktový placeholder pre horčík citrát GymBeam',
        ],
        'pros' => ['dobrá vstrebateľnosť', 'praktický all-round variant'],
        'cons' => ['u citlivejších ľudí môže viac rozhýbať trávenie'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'myprotein-magnesium-malate' => [
        'slug' => 'myprotein-magnesium-malate',
        'name' => 'Magnézium malát',
        'merchant' => 'Myprotein',
        'merchant_slug' => 'myprotein',
        'category' => 'mineraly',
        'affiliate_code' => 'horcik-ktory-je-najlepsi-a-preco-myprotein',
        'fallback_url' => 'https://www.myprotein.sk/',
        'summary' => 'Forma vhodnejšia na denný režim a energickejší profil.',
        'image' => [
            'asset' => 'img/products/myprotein-magnesium-malate/main.webp',
            'alt' => 'Produktový placeholder pre horčík malát Myprotein',
        ],
        'pros' => ['hodí sa skôr cez deň', 'dobrý kompromis pri únave'],
        'cons' => ['menej vhodný na večerný relax'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'aktin-balanced-preworkout' => [
        'slug' => 'aktin-balanced-preworkout',
        'name' => 'Balanced stim pre-workout',
        'merchant' => 'Aktin',
        'merchant_slug' => 'aktin',
        'category' => 'pre-workout',
        'affiliate_code' => 'pre-workout-ako-vybrat-aktin',
        'fallback_url' => 'https://www.aktin.sk/',
        'summary' => 'Balanced predtréningovka pre väčšinu tréningov bez extrémneho stimu.',
        'image' => [
            'asset' => 'img/products/aktin-balanced-preworkout/main.webp',
            'alt' => 'Produktový placeholder pre balanced pre-workout Aktin',
        ],
        'pros' => ['vhodné pre väčšinu tréningov', 'nižšie riziko prestreleného kofeínu'],
        'cons' => ['pre heavy stim fanúšikov môže byť miernejší'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'gymbeam-high-stim-preworkout' => [
        'slug' => 'gymbeam-high-stim-preworkout',
        'name' => 'High-stim pre-workout',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'pre-workout',
        'affiliate_code' => 'pre-workout-ako-vybrat-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/',
        'summary' => 'Silnejší stimulant pre náročnejšie tréningy a vyššiu toleranciu kofeínu.',
        'image' => [
            'asset' => 'img/products/gymbeam-high-stim-preworkout/main.webp',
            'alt' => 'Produktový placeholder pre high-stim pre-workout GymBeam',
        ],
        'pros' => ['výraznejší nakopávací efekt', 'dobré do náročných session'],
        'cons' => ['nevhodné neskoro večer'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'myprotein-non-stim-pump' => [
        'slug' => 'myprotein-non-stim-pump',
        'name' => 'Non-stim pump formula',
        'merchant' => 'Myprotein',
        'merchant_slug' => 'myprotein',
        'category' => 'pre-workout',
        'affiliate_code' => 'pre-workout-ako-vybrat-myprotein',
        'fallback_url' => 'https://www.myprotein.sk/',
        'summary' => 'Non-stim voľba pre večerný tréning alebo citlivosť na kofeín.',
        'image' => [
            'asset' => 'img/products/myprotein-non-stim-pump/main.webp',
            'alt' => 'Produktový placeholder pre non-stim pre-workout Myprotein',
        ],
        'pros' => ['bez kofeínu', 'lepšia kontrola pri večernom tréningu'],
        'cons' => ['nemá klasický stimulantový feel'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'aktin-probiotics-multistrain' => [
        'slug' => 'aktin-probiotics-multistrain',
        'name' => 'Multi-strain probiotiká',
        'merchant' => 'Aktin',
        'merchant_slug' => 'aktin',
        'category' => 'probiotika-travenie',
        'affiliate_code' => 'probiotika-ako-vybrat-aktin',
        'fallback_url' => 'https://www.aktin.sk/',
        'summary' => 'Širší kmeňový profil pre každodenné dlhšie užívanie.',
        'image' => [
            'asset' => 'img/products/aktin-probiotics-multistrain/main.webp',
            'alt' => 'Produktový placeholder pre multistrain probiotiká Aktin',
        ],
        'pros' => ['viac kmeňov v jednom produkte', 'dobrý základ pre dlhodobé používanie'],
        'cons' => ['počet kmeňov nie je všetko bez správnej indikácie'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'gymbeam-probiotics-everyday' => [
        'slug' => 'gymbeam-probiotics-everyday',
        'name' => 'Everyday digestion probiotiká',
        'merchant' => 'GymBeam',
        'merchant_slug' => 'gymbeam',
        'category' => 'probiotika-travenie',
        'affiliate_code' => 'probiotika-ako-vybrat-gymbeam',
        'fallback_url' => 'https://gymbeam.sk/',
        'summary' => 'Praktický everyday variant pri dlhšom režime a citlivejšom trávení.',
        'image' => [
            'asset' => 'img/products/gymbeam-probiotics-everyday/main.webp',
            'alt' => 'Produktový placeholder pre everyday probiotiká GymBeam',
        ],
        'pros' => ['praktické dávkovanie', 'dobrá everyday voľba'],
        'cons' => ['nie je to špecializovaná voľba po antibiotikách'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
    'myprotein-probiotics-capsules' => [
        'slug' => 'myprotein-probiotics-capsules',
        'name' => 'Probiotiká / cestovné kapsuly',
        'merchant' => 'Myprotein',
        'merchant_slug' => 'myprotein',
        'category' => 'probiotika-travenie',
        'affiliate_code' => 'probiotika-ako-vybrat-myprotein',
        'fallback_url' => 'https://www.myprotein.sk/',
        'summary' => 'Jednoduché kapsuly s praktickým balením na bežný režim alebo cestovanie.',
        'image' => [
            'asset' => 'img/products/myprotein-probiotics-capsules/main.webp',
            'alt' => 'Produktový placeholder pre probiotiká Myprotein',
        ],
        'pros' => ['praktické balenie', 'jednoduché užívanie'],
        'cons' => ['menej výrazný obsah pri špecializovaných požiadavkách'],
        'feed_source' => 'dognet-ready',
        'merchant_product_id' => null,
        'image_source' => 'merchant',
    ],
];