<?php
declare(strict_types=1);

return [
    'symprove' => [
        'name' => 'Symprove',
        'aliases' => ['sym prove'],
        'hosts' => ['symprove.sk', 'symprove.com'],
        'network' => 'dognet',
        'affiliate_supported' => true,
        'campaign_id' => 5307,
        'campaign_status' => 'approved',
        'feed_url' => 'https://storage.feedyio.com/bencos-prod.myshopify.com/671a474061c66d5e4c25540d.xml',
        'campaign_public_url' => 'https://www.dognet.sk/',
        'feed_available' => true,
    ],
    'protein' => [
        'name' => 'Protein.sk',
        'aliases' => ['protein.sk', 'protein sk', 'protein-sk', 'proteinsk'],
        'hosts' => ['protein.sk'],
        'network' => 'dognet',
        'affiliate_supported' => true,
        'campaign_id' => 4341,
        'campaign_status' => 'approved',
        'feed_url' => 'https://www.protein.sk/feed/heureka.xml',
        'campaign_public_url' => 'https://www.dognet.sk/',
        'feed_available' => true,
    ],
    'gymbeam' => [
        'name' => 'GymBeam',
        'aliases' => ['gym beam'],
        'hosts' => ['gymbeam.sk', 'gymbeam.cz', 'gymbeam.hu', 'gymbeam.ro'],
        'network' => 'dognet',
        'affiliate_supported' => true,
        'campaign_id' => 4101,
        'campaign_status' => 'approved',
        'feed_url' => 'https://feeds.mergado.com/gymbeam-sk-heureka-sk-25a5938cc07b86d54c672eb682703196.xml',
        'campaign_public_url' => 'https://www.dognet.sk/kampane/kampan-gymbeam-sk/',
        'tracking' => 's2s',
        'cookie_days' => 10,
        'validation_days' => 75,
        'available_markets' => ['sk'],
        'feed_available' => true,
        'promotional_assets' => ['xml-feed', 'banners', 'coupons', 'pr-articles', 'email-templates'],
        'notes' => [
            'clean-internal-links-only',
            'keep-all-dognet-tracking-parameters',
            'direct-ppc-restricted',
        ],
    ],
    'ironaesthetics' => [
        'name' => 'Iron Aesthetics',
        'aliases' => ['iron aesthetics'],
        'hosts' => ['ironaesthetics.sk', 'ironaesthetics.cz'],
        'network' => 'dognet',
        'affiliate_supported' => true,
        'campaign_id' => 1873,
        'campaign_status' => 'approved',
        'feed_url' => 'https://ironaesthetics.sk/modules/gmerchantfeed/xml/gmsk.xml',
        'campaign_public_url' => 'https://www.dognet.sk/',
        'feed_available' => true,
    ],
    'imunoklub' => [
        'name' => 'Imunoklub',
        'aliases' => ['imuno klub'],
        'hosts' => ['imunoklub.sk'],
        'network' => 'dognet',
        'affiliate_supported' => true,
        'campaign_id' => 1815,
        'campaign_status' => 'approved',
        'feed_url' => 'https://www.imunoklub.sk/feeds/google-merchant.xml',
        'campaign_public_url' => 'https://www.dognet.sk/',
        'feed_available' => true,
    ],
    'aktin' => [
        'name' => 'Aktin',
        'aliases' => ['vilgain'],
        'hosts' => ['aktin.sk', 'aktin.cz', 'vilgain.sk', 'vilgain.cz'],
        'network' => 'manual-or-other',
        'affiliate_supported' => false,
        'campaign_status' => 'manual',
        'feed_available' => false,
    ],
    'myprotein' => [
        'name' => 'Myprotein',
        'aliases' => ['my protein'],
        'hosts' => ['myprotein.sk', 'myprotein.cz', 'myprotein.com'],
        'network' => 'manual-or-other',
        'affiliate_supported' => false,
        'campaign_status' => 'manual',
        'feed_available' => false,
    ],
];
